language: python

matrix:
    include:
        - os: linux
          sudo: required
          python: 2.7
          cache: pip
          virtualenv:
              system_site_packages: true
        - os: linux
          sudo: required
          python: 3.5
          cache: pip
        - os: osx
          osx_image: xcode7.3
          language: generic
          python: 2.7
        - os: osx
          osx_image: xcode7.3
          language: generic
          python: 3.5

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install portaudio ;fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -O http://www.portaudio.com/archives/pa_stable_v190600_20161030.tgz; tar -xvf pa_stable_v190600_20161030.tgz; cd portaudio; ./configure; make; sudo make install; cd -;fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install portaudio19-dev; fi
    - pip install --upgrade numpy setuptools aubio pyaudio
install:
    #- if [[ "$TRAVIS_PYTHON_VERSION" == 3.5 ]]; then sudo apt-get -y install python3-pyqt5; fi
    #- if [[ "$TRAVIS_PYTHON_VERSION" == 2.7 ]]; then sudo apt-get -y install python-pyqt5; fi
    - if [[ "$TRAVIS_PYTHON_VERSION" == 3.5 ]]; then sudo python3 setup.py install; fi
    - if [[ "$TRAVIS_PYTHON_VERSION" == 2.7 ]]; then sudo python setup.py install; fi

script:
    - if [[ "$TRAVIS_PYTHON_VERSION" == 3.5 ]]; then python3 test/test_all.py; fi
    - if [[ "$TRAVIS_PYTHON_VERSION" == 2.7 ]]; then python test/test_all.py; fi

notifications:
    email: false
